services:

  catalog-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog_service
    ports:
      - 5433:5432
    networks:
      - borrow-hub-network

networks:
  borrow-hub-network:
    external: true